create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'admin',
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  deactivated_by uuid references auth.users(id) on delete set null,
  deactivated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_users_role_check
    check (role in ('admin', 'super_admin')),
  constraint admin_users_email_not_blank
    check (length(btrim(email)) > 0)
);

create table if not exists public.course_purchase_requests (
  id uuid primary key default gen_random_uuid(),
  request_number bigint generated by default as identity unique,
  reference_code text generated always as ('EG-MC-' || lpad(request_number::text, 6, '0')) stored unique,
  member_id uuid not null references public.profiles(id) on delete cascade,
  member_email text not null,
  member_name text not null,
  course_slug text not null default 'master-class',
  amount_thb integer not null default 12900,
  status text not null default 'payment_started',
  slip_storage_path text,
  slip_file_name text,
  transfer_note text,
  submitted_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  review_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint course_purchase_requests_course_check
    check (course_slug = 'master-class'),
  constraint course_purchase_requests_amount_check
    check (amount_thb > 0),
  constraint course_purchase_requests_status_check
    check (status in ('payment_started', 'pending_review', 'approved', 'rejected')),
  constraint course_purchase_requests_member_course_unique
    unique (member_id, course_slug)
);

create table if not exists public.course_entitlements (
  id uuid primary key default gen_random_uuid(),
  member_id uuid not null references public.profiles(id) on delete cascade,
  course_slug text not null default 'master-class',
  purchase_request_id uuid references public.course_purchase_requests(id) on delete set null,
  granted_by uuid references auth.users(id) on delete set null,
  granted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint course_entitlements_course_check
    check (course_slug = 'master-class'),
  constraint course_entitlements_member_course_unique
    unique (member_id, course_slug)
);

create table if not exists public.course_purchase_admin_events (
  id uuid primary key default gen_random_uuid(),
  event_type text not null,
  actor_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  purchase_request_id uuid references public.course_purchase_requests(id) on delete cascade,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint course_purchase_admin_events_type_check
    check (
      event_type in (
        'purchase_started',
        'slip_submitted',
        'purchase_approved',
        'purchase_rejected',
        'admin_added',
        'admin_deactivated'
      )
    )
);

create index if not exists admin_users_active_role_idx
  on public.admin_users (is_active, role);

create index if not exists admin_users_email_idx
  on public.admin_users (lower(email));

create index if not exists course_purchase_requests_status_created_idx
  on public.course_purchase_requests (status, created_at desc);

create index if not exists course_purchase_requests_member_idx
  on public.course_purchase_requests (member_id, created_at desc);

create index if not exists course_entitlements_member_idx
  on public.course_entitlements (member_id, course_slug);

create index if not exists course_purchase_admin_events_purchase_idx
  on public.course_purchase_admin_events (purchase_request_id, created_at desc);

create or replace function private.is_elite_admin(required_role text default null)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
      and is_active = true
      and (
        required_role is null
        or role = required_role
        or (required_role = 'admin' and role = 'super_admin')
      )
  );
$$;

create or replace function private.current_elite_admin_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select role
  from public.admin_users
  where user_id = (select auth.uid())
    and is_active = true
  order by
    case role
      when 'super_admin' then 0
      else 1
    end
  limit 1;
$$;

create or replace function private.touch_admin_user_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function private.touch_course_purchase_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists admin_users_touch_updated_at on public.admin_users;
create trigger admin_users_touch_updated_at
  before update on public.admin_users
  for each row
  execute function private.touch_admin_user_updated_at();

drop trigger if exists course_purchase_requests_touch_updated_at on public.course_purchase_requests;
create trigger course_purchase_requests_touch_updated_at
  before update on public.course_purchase_requests
  for each row
  execute function private.touch_course_purchase_updated_at();

alter table public.admin_users enable row level security;
alter table public.course_purchase_requests enable row level security;
alter table public.course_entitlements enable row level security;
alter table public.course_purchase_admin_events enable row level security;

drop policy if exists "Admins can read admin users" on public.admin_users;
create policy "Admins can read admin users"
  on public.admin_users
  for select
  to authenticated
  using (private.is_elite_admin('admin'));

drop policy if exists "Super admins can insert admin users" on public.admin_users;
create policy "Super admins can insert admin users"
  on public.admin_users
  for insert
  to authenticated
  with check (private.is_elite_admin('super_admin'));

drop policy if exists "Super admins can update admin users" on public.admin_users;
create policy "Super admins can update admin users"
  on public.admin_users
  for update
  to authenticated
  using (private.is_elite_admin('super_admin'))
  with check (private.is_elite_admin('super_admin'));

drop policy if exists "Members can read own course purchase requests" on public.course_purchase_requests;
create policy "Members can read own course purchase requests"
  on public.course_purchase_requests
  for select
  to authenticated
  using (member_id = (select auth.uid()));

drop policy if exists "Admins can read course purchase requests" on public.course_purchase_requests;
create policy "Admins can read course purchase requests"
  on public.course_purchase_requests
  for select
  to authenticated
  using (private.is_elite_admin('admin'));

drop policy if exists "Members can start own course purchase" on public.course_purchase_requests;
create policy "Members can start own course purchase"
  on public.course_purchase_requests
  for insert
  to authenticated
  with check (
    member_id = (select auth.uid())
    and course_slug = 'master-class'
    and status = 'payment_started'
  );

drop policy if exists "Members can submit own course purchase slip" on public.course_purchase_requests;
create policy "Members can submit own course purchase slip"
  on public.course_purchase_requests
  for update
  to authenticated
  using (
    member_id = (select auth.uid())
    and status in ('payment_started', 'rejected')
  )
  with check (
    member_id = (select auth.uid())
    and course_slug = 'master-class'
    and status = 'pending_review'
  );

drop policy if exists "Admins can update course purchase requests" on public.course_purchase_requests;
create policy "Admins can update course purchase requests"
  on public.course_purchase_requests
  for update
  to authenticated
  using (private.is_elite_admin('admin'))
  with check (private.is_elite_admin('admin'));

drop policy if exists "Members can read own course entitlements" on public.course_entitlements;
create policy "Members can read own course entitlements"
  on public.course_entitlements
  for select
  to authenticated
  using (member_id = (select auth.uid()));

drop policy if exists "Admins can read course entitlements" on public.course_entitlements;
create policy "Admins can read course entitlements"
  on public.course_entitlements
  for select
  to authenticated
  using (private.is_elite_admin('admin'));

drop policy if exists "Admins can insert course entitlements" on public.course_entitlements;
create policy "Admins can insert course entitlements"
  on public.course_entitlements
  for insert
  to authenticated
  with check (private.is_elite_admin('admin'));

drop policy if exists "Admins can update course entitlements" on public.course_entitlements;
create policy "Admins can update course entitlements"
  on public.course_entitlements
  for update
  to authenticated
  using (private.is_elite_admin('admin'))
  with check (private.is_elite_admin('admin'));

drop policy if exists "Admins can read course purchase admin events" on public.course_purchase_admin_events;
create policy "Admins can read course purchase admin events"
  on public.course_purchase_admin_events
  for select
  to authenticated
  using (private.is_elite_admin('admin'));

drop policy if exists "Admins can insert course purchase admin events" on public.course_purchase_admin_events;
create policy "Admins can insert course purchase admin events"
  on public.course_purchase_admin_events
  for insert
  to authenticated
  with check (private.is_elite_admin('admin'));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'course-payment-slips',
  'course-payment-slips',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Members can upload own course payment slips" on storage.objects;
create policy "Members can upload own course payment slips"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'course-payment-slips'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Members can read own course payment slips" on storage.objects;
create policy "Members can read own course payment slips"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'course-payment-slips'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Admins can read course payment slips" on storage.objects;
create policy "Admins can read course payment slips"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'course-payment-slips'
    and private.is_elite_admin('admin')
  );

revoke all on table public.admin_users from anon, authenticated;
revoke all on table public.course_purchase_requests from anon, authenticated;
revoke all on table public.course_entitlements from anon, authenticated;
revoke all on table public.course_purchase_admin_events from anon, authenticated;

grant usage on schema public to authenticated;
grant select, insert, update on table public.admin_users to authenticated;
grant select, insert, update on table public.course_purchase_requests to authenticated;
grant select, insert, update on table public.course_entitlements to authenticated;
grant select, insert on table public.course_purchase_admin_events to authenticated;

insert into public.admin_users (user_id, email, role, is_active)
select users.id, users.email, 'super_admin', true
from auth.users as users
where lower(users.email) = 'komsupanat.poom@gmail.com'
on conflict (user_id) do update
set
  email = excluded.email,
  role = 'super_admin',
  is_active = true,
  deactivated_by = null,
  deactivated_at = null,
  updated_at = now();

comment on table public.admin_users is
  'Active Elite Gold admin roles. Role data is intentionally separate from editable member profiles.';

comment on table public.course_purchase_requests is
  'Manual bank-transfer purchase requests for the Master Class Education MVP.';

comment on table public.course_entitlements is
  'Course access grants created after manual payment approval.';

comment on table public.course_purchase_admin_events is
  'Append-only admin and purchase audit events for the manual course purchase flow.';
